version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/setup_systemd.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/after_install.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
