version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running unit tests...
      - nohup python app/app.py &
      - sleep 3
      - curl -f http://localhost:5000/
      - pkill -f "python app.py"
      - echo Packaging app for deployment...
      - zip -r deployment-package.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deployment-package.zip
