version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - echo Installing sass compiler...
      - npm install -g sass
      - echo Installing redis...
      - sudo yum update -y && sudo yum install -y epel-release redis-server
      - sudo systemctl start redis

  build:
    commands:
      - echo Building static assets...
      - mkdir -p static
      - sass static_src/style.scss static/style.css --no-source-map --style=compressed
      - cp static_src/banner.png static/banner.png      
      - echo Running unit tests...
      - nohup python app/app.py &
      - sleep 2
      - curl -f http://localhost:80/
      - echo Packaging app for deployment...
      - zip -r deployment-package.zip app scripts static templates appspec.yml requirements.txt 
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - deployment-package.zip
